### ISSUE TITLE
AVFoundation

### ISSUE THREAD

**Issue by glungtung** [urshofer/ofxGaplessVideo#1]
Hi,
Nice addon !
With last OF on github, is it still required to replace AVFoundation with your patched version ?
Thanks

**Comment by glungtung** [comment]
I did not have a look at the diff between files, but can I patch my AVFoundationPlayer and still safely use it for a classical single-threaded videoplayer app ?

**Comment by urshofer** [comment]
hi
it should work w/o patching. the Patches found their way into the Master branch of openframeworks...
best
Urs
